name: obj_detection
description: "To test various tflite models for object detection"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image: ^4.2.0
  image_picker: ^1.1.2
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/efficientdet/
    - assets/yolov8-detection/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/Lato-Regular.ttf
        - asset: assets/Lato-Bold.ttf
          weight: 700
